import { PageHeader } from '@/components/page-header';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent } from '@/components/ui/card';
import AppLayout from '@/layouts/app-layout';
import { type BreadcrumbItem } from '@/types';
import { Head } from '@inertiajs/react';
import { Sparkles, TriangleAlert } from 'lucide-react';

const breadcrumbs: BreadcrumbItem[] = [{ title: 'AI', href: '/ai' }];

type FeatureUsage = {
    feature: string;
    requests: number;
    tokens: number;
    cost: number;
};

type UserUsage = {
    user_id: number | null;
    requests: number;
    cost: number;
};

type Usage = {
    total_requests: number;
    failed_requests: number;
    total_tokens: number;
    total_cost: number;
    by_feature: FeatureUsage[];
    by_user: UserUsage[];
};

type Driver = {
    name: string;
    model: string;
    live: boolean;
};

type Credits = {
    used: number;
    /** `null` means the plan grants unlimited AI credits. */
    remaining: number | null;
};

type Calibration = {
    insufficient_data: boolean;
    required_per_bucket: number;
    won: { count: number; avg_score: number | null };
    lost: { count: number; avg_score: number | null };
    separation: number | null;
};

type RecentRequest = {
    id: number;
    feature: string;
    model: string;
    tokens: number;
    cost: number;
    duration_ms: number | null;
    attempts: number;
    status: string;
    error: string | null;
    created_at: string | null;
};

function money(cents: number): string {
    return `$${(cents / 100).toFixed(2)}`;
}

function formatTime(iso: string | null): string {
    return iso === null ? '—' : new Date(iso).toLocaleString();
}

function statusVariant(status: string): 'default' | 'secondary' | 'destructive' {
    if (status === 'failed') return 'destructive';
    if (status === 'succeeded') return 'default';
    return 'secondary';
}

/**
 * The driver banner is deliberately loud. Fixture output reads like a real
 * completion, so the page states in plain words when nothing was inferred by a
 * language model.
 */
function DriverNotice({ driver }: { driver: Driver }) {
    if (!driver.live) {
        return (
            <Alert variant="destructive" className="border-destructive bg-destructive/10">
                <TriangleAlert className="h-4 w-4" />
                <AlertTitle className="text-base">Fixture model — this is not a live language model</AlertTitle>
                <AlertDescription className="space-y-1">
                    <p>
                        Every completion on these pages is produced by the <span className="font-medium">{driver.name}</span> fixture driver (
                        {driver.model}). The text is canned output, not inference. Do not treat it as a real answer, a real score or real research,
                        and do not send it to a customer.
                    </p>
                    <p>Configure a live provider before relying on any AI output.</p>
                </AlertDescription>
            </Alert>
        );
    }

    return (
        <Alert>
            <Sparkles className="h-4 w-4" />
            <AlertTitle>Live provider</AlertTitle>
            <AlertDescription>
                Completions are generated by <span className="font-medium">{driver.name}</span> using model{' '}
                <span className="font-medium">{driver.model}</span>.
            </AlertDescription>
        </Alert>
    );
}

function CreditsCard({ credits }: { credits: Credits }) {
    const unlimited = credits.remaining === null;
    const exhausted = credits.remaining === 0;

    return (
        <Card>
            <CardContent className="flex flex-wrap items-center justify-between gap-4 p-4">
                <div>
                    <p className="text-muted-foreground text-sm">AI credits used</p>
                    <p className="text-2xl font-semibold">{credits.used}</p>
                </div>
                <div>
                    <p className="text-muted-foreground text-sm">Remaining</p>
                    <p className="text-2xl font-semibold">{unlimited ? 'Unlimited' : credits.remaining}</p>
                </div>
                <div className="min-w-48 flex-1">
                    {unlimited ? (
                        <Badge variant="secondary">No credit cap on this plan</Badge>
                    ) : exhausted ? (
                        <div className="space-y-1">
                            <Badge variant="destructive">Credits exhausted</Badge>
                            <p className="text-destructive text-sm">AI calls will be refused until the allowance resets or the plan is upgraded.</p>
                        </div>
                    ) : (
                        <Badge variant="default">{credits.remaining} credits left</Badge>
                    )}
                </div>
            </CardContent>
        </Card>
    );
}

/**
 * AISA-012/013: advisory-score quality as the tenant's OWN measured number —
 * scored deals versus their actual outcomes — never a claim from the platform.
 */
function CalibrationCard({ calibration }: { calibration: Calibration }) {
    return (
        <Card>
            <CardContent className="space-y-2 p-4">
                <p className="text-sm font-medium">Advisory score calibration</p>
                {calibration.insufficient_data ? (
                    <p className="text-muted-foreground text-sm">
                        Not enough evidence yet: calibration needs at least {calibration.required_per_bucket} AI-scored deals that were won and{' '}
                        {calibration.required_per_bucket} that were lost (so far {calibration.won.count} won, {calibration.lost.count} lost). Until
                        then, no quality figure is shown — an unmeasured claim would be fiction.
                    </p>
                ) : (
                    <div className="flex flex-wrap gap-6">
                        <div>
                            <p className="text-muted-foreground text-sm">Won deals ({calibration.won.count})</p>
                            <p className="text-2xl font-semibold">{calibration.won.avg_score}</p>
                            <p className="text-muted-foreground text-xs">avg advisory score</p>
                        </div>
                        <div>
                            <p className="text-muted-foreground text-sm">Lost deals ({calibration.lost.count})</p>
                            <p className="text-2xl font-semibold">{calibration.lost.avg_score}</p>
                            <p className="text-muted-foreground text-xs">avg advisory score</p>
                        </div>
                        <div>
                            <p className="text-muted-foreground text-sm">Separation</p>
                            <p className="text-2xl font-semibold">
                                {calibration.separation !== null && calibration.separation > 0 ? '+' : ''}
                                {calibration.separation}
                            </p>
                            <p className="text-muted-foreground text-xs">won minus lost — higher means the score discriminates</p>
                        </div>
                    </div>
                )}
            </CardContent>
        </Card>
    );
}

export default function AiDashboard({
    usage,
    driver,
    credits,
    recent,
    calibration,
}: {
    usage: Usage;
    driver: Driver;
    credits: Credits;
    recent: RecentRequest[];
    calibration: Calibration;
}) {
    const totals: { label: string; value: string | number }[] = [
        { label: 'Requests', value: usage.total_requests },
        { label: 'Failed', value: usage.failed_requests },
        { label: 'Tokens', value: usage.total_tokens },
        { label: 'Estimated cost', value: money(usage.total_cost) },
    ];

    return (
        <AppLayout breadcrumbs={breadcrumbs}>
            <Head title="AI" />
            <div className="space-y-6 p-4">
                <PageHeader title="AI" description="Provider status, credit consumption and every request the platform has made." />

                <DriverNotice driver={driver} />

                <CreditsCard credits={credits} />

                <CalibrationCard calibration={calibration} />

                <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">
                    {totals.map((total) => (
                        <Card key={total.label}>
                            <CardContent className="p-4">
                                <p className="text-muted-foreground text-sm">{total.label}</p>
                                <p className="text-2xl font-semibold">{total.value}</p>
                            </CardContent>
                        </Card>
                    ))}
                </div>

                <div>
                    <h3 className="mb-2 text-sm font-medium">Usage by feature</h3>
                    {usage.by_feature.length === 0 ? (
                        <p className="text-muted-foreground text-sm">No AI requests yet. Features appear here once the platform calls a model.</p>
                    ) : (
                        <div className="overflow-x-auto rounded-lg border">
                            <table className="w-full text-left text-sm">
                                <thead className="bg-muted/50 text-muted-foreground">
                                    <tr>
                                        <th className="p-3 font-medium">Feature</th>
                                        <th className="p-3 text-center font-medium">Requests</th>
                                        <th className="p-3 text-center font-medium">Tokens</th>
                                        <th className="p-3 text-center font-medium">Cost</th>
                                    </tr>
                                </thead>
                                <tbody className="divide-y">
                                    {usage.by_feature.map((row) => (
                                        <tr key={row.feature} className="hover:bg-muted/40">
                                            <td className="p-3 font-medium">{row.feature}</td>
                                            <td className="p-3 text-center">{row.requests}</td>
                                            <td className="p-3 text-center">{row.tokens}</td>
                                            <td className="text-muted-foreground p-3 text-center">{money(row.cost)}</td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                    )}
                </div>

                <div>
                    <h3 className="mb-2 text-sm font-medium">Usage by user</h3>
                    {usage.by_user.length === 0 ? (
                        <p className="text-muted-foreground text-sm">No attributed usage yet.</p>
                    ) : (
                        <div className="overflow-x-auto rounded-lg border">
                            <table className="w-full text-left text-sm">
                                <thead className="bg-muted/50 text-muted-foreground">
                                    <tr>
                                        <th className="p-3 font-medium">User</th>
                                        <th className="p-3 text-center font-medium">Requests</th>
                                        <th className="p-3 text-center font-medium">Cost</th>
                                    </tr>
                                </thead>
                                <tbody className="divide-y">
                                    {usage.by_user.map((row) => (
                                        <tr key={row.user_id ?? 'system'} className="hover:bg-muted/40">
                                            <td className="p-3 font-medium">{row.user_id === null ? 'System' : `User #${row.user_id}`}</td>
                                            <td className="p-3 text-center">{row.requests}</td>
                                            <td className="text-muted-foreground p-3 text-center">{money(row.cost)}</td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                    )}
                </div>

                <div>
                    <h3 className="mb-2 text-sm font-medium">Recent requests</h3>
                    {recent.length === 0 ? (
                        <p className="text-muted-foreground text-sm">No requests logged yet. Every model call is recorded here with its cost.</p>
                    ) : (
                        <div className="overflow-x-auto rounded-lg border">
                            <table className="w-full text-left text-sm">
                                <thead className="bg-muted/50 text-muted-foreground">
                                    <tr>
                                        <th className="p-3 font-medium">Feature</th>
                                        <th className="p-3 font-medium">Model</th>
                                        <th className="p-3 text-center font-medium">Tokens</th>
                                        <th className="p-3 text-center font-medium">Cost</th>
                                        <th className="p-3 text-center font-medium">Duration</th>
                                        <th className="p-3 text-center font-medium">Attempts</th>
                                        <th className="p-3 font-medium">Status</th>
                                        <th className="p-3 font-medium">When</th>
                                    </tr>
                                </thead>
                                <tbody className="divide-y">
                                    {recent.map((request) => (
                                        <tr key={request.id} className="hover:bg-muted/40 align-top">
                                            <td className="p-3 font-medium">{request.feature}</td>
                                            <td className="text-muted-foreground p-3">{request.model}</td>
                                            <td className="p-3 text-center">{request.tokens}</td>
                                            <td className="text-muted-foreground p-3 text-center">{money(request.cost)}</td>
                                            <td className="text-muted-foreground p-3 text-center">
                                                {request.duration_ms === null ? '—' : `${request.duration_ms} ms`}
                                            </td>
                                            <td className="p-3 text-center">{request.attempts}</td>
                                            <td className="p-3">
                                                <Badge variant={statusVariant(request.status)}>{request.status}</Badge>
                                                {request.error !== null && <p className="text-destructive mt-1 max-w-64 text-xs">{request.error}</p>}
                                            </td>
                                            <td className="text-muted-foreground p-3">{formatTime(request.created_at)}</td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                    )}
                </div>
            </div>
        </AppLayout>
    );
}
