<?php

declare(strict_types=1);

/**
 * Digital PR + Link Building close-out (Phase 45 — DPR-003/004/009,
 * LINK-001/002/003).
 *
 * The backlink audit over the link-index seam (fixture-tested like every
 * provider) with first-party verified links, toxic flags + Google-format
 * disavow export, competitor gaps feeding outreach; expert-commentary
 * pitches drafted from real profiles, the industry-publication starter list,
 * and research stories compiled from the tenant's own aggregates.
 */

use App\Models\BrandProfile;
use App\Models\Competitor;
use App\Models\Contact;
use App\Models\ContentPiece;
use App\Models\ExpertProfile;
use App\Models\OutreachCampaign;
use App\Models\OutreachProspect;
use App\Services\Seo\BacklinkAuditService;
use App\Support\CurrentOrganization;

beforeEach(function () {
    [$this->org, $this->owner] = makeOrganization('DprLink Org');
    subscribeOrganization($this->org, 'enterprise');
    app(CurrentOrganization::class)->set($this->org);
});

afterEach(fn () => app(CurrentOrganization::class)->forget());

it('audits the link profile through the seam, flags toxicity with reasons, and exports the disavow file', function () {
    BrandProfile::first()?->update(['website_url' => 'https://acme-msp.example']) ?? BrandProfile::create(['website_url' => 'https://acme-msp.example']);

    // First-party verified links are real regardless of driver.
    $campaign = OutreachCampaign::create(['name' => 'Links', 'type' => 'link_building']);
    $campaign->prospects()->create(['name' => 'MSP Insider', 'domain' => 'msp-insider.example', 'status' => 'won', 'placement_url' => 'https://msp-insider.example/feature']);

    $audit = app(BacklinkAuditService::class)->audit();

    expect($audit['domain'])->toBe('acme-msp.example')
        ->and($audit['provider'])->toBe('fixture')
        ->and($audit['links'])->not->toBeEmpty()
        ->and($audit['toxic'])->toBeGreaterThan(0)
        ->and($audit['referring_domains'])->toBeGreaterThan(0)
        ->and(collect($audit['verified'])->pluck('source'))->toContain('msp-insider.example');

    // Every toxic flag names its reason.
    $toxicRow = collect($audit['links'])->firstWhere('toxic', true);
    expect($toxicRow['reasons'])->not->toBeEmpty();

    // LINK-002: the disavow export is Google's actual format.
    $txt = $this->actingAs($this->owner)->get(route('seo.links.disavow'))
        ->assertOk()->streamedContent();
    expect($txt)->toContain('domain:')
        ->and($txt)->toContain('# Disavow file generated by Piotrack');
    foreach (collect($audit['links'])->where('toxic', true)->pluck('source_domain')->unique() as $domain) {
        expect($txt)->toContain('domain:'.$domain);
    }

    // The page carries the audit and labels the fixture driver.
    $props = $this->actingAs($this->owner)->get(route('seo.links.index'))->assertOk()->viewData('page')['props'];
    expect($props['audit']['provider'])->toBe('fixture');
});

it('finds competitor link gaps and turns one into an outreach prospect', function () {
    BrandProfile::first()?->update(['website_url' => 'https://acme-msp.example']) ?? BrandProfile::create(['website_url' => 'https://acme-msp.example']);
    Competitor::create(['name' => 'Rival IT', 'domain' => 'rival-it.example', 'is_tracked' => true]);

    $gaps = app(BacklinkAuditService::class)->competitorGaps();
    expect($gaps)->not->toBeEmpty()
        ->and(collect($gaps)->pluck('competitor')->unique()->all())->toBe(['Rival IT'])
        // Toxic sources never appear as outreach suggestions.
        ->and(collect($gaps)->filter(fn (array $g) => str_ends_with($g['source_domain'], '.xyz')))->toBeEmpty();

    $gap = $gaps[0];
    $this->actingAs($this->owner)->post(route('seo.links.prospect'), [
        'source_domain' => $gap['source_domain'], 'domain_authority' => $gap['domain_authority'],
    ])->assertRedirect();

    $prospect = OutreachProspect::where('domain', $gap['source_domain'])->firstOrFail();
    expect($prospect->status)->toBe('identified')
        ->and($prospect->campaign()->firstOrFail()->name)->toBe('Competitor link gaps');

    // Idempotent — clicking twice never duplicates.
    $this->actingAs($this->owner)->post(route('seo.links.prospect'), ['source_domain' => $gap['source_domain']])->assertRedirect();
    expect(OutreachProspect::where('domain', $gap['source_domain'])->count())->toBe(1);
});

it('seeds the industry-publication starter list into a digital-PR campaign', function () {
    $campaign = OutreachCampaign::create(['name' => 'PR push', 'type' => 'digital_pr']);

    $this->actingAs($this->owner)->post(route('content.outreach.seed-publications', $campaign))->assertRedirect();

    $domains = $campaign->prospects()->pluck('domain');
    expect($domains)->toContain('crn.com')
        ->and($domains)->toContain('msspalert.com')
        ->and($campaign->prospects()->count())->toBe(7);

    // Idempotent re-seed adds nothing.
    $this->actingAs($this->owner)->post(route('content.outreach.seed-publications', $campaign))->assertRedirect();
    expect($campaign->prospects()->count())->toBe(7);
});

it('drafts expert-commentary pitches from the real expert profile', function () {
    $campaign = OutreachCampaign::create(['name' => 'Commentary', 'type' => 'expert_commentary']);
    $prospect = $campaign->prospects()->create(['name' => 'ChannelE2E', 'domain' => 'channele2e.com', 'status' => 'identified']);
    $expert = ExpertProfile::create([
        'name' => 'Priya Nair', 'title' => 'CISO', 'is_active' => true,
        'credentials' => ['CISSP', 'CISM'], 'knows_about' => ['ransomware response', 'zero trust', 'compliance'],
    ]);

    $this->actingAs($this->owner)->post(route('content.outreach.prospects.pitch', $prospect), [
        'expert_profile_id' => $expert->id,
    ])->assertRedirect();

    $pitch = (string) $prospect->refresh()->pitch;
    expect($pitch)->toContain('Priya Nair (CISO)')
        ->and($pitch)->toContain('ransomware response, zero trust, compliance')
        ->and($pitch)->toContain('CISSP, CISM')
        ->and($pitch)->toContain('ChannelE2E');
});

it('compiles research stories from the tenant\'s own aggregates behind a data floor', function () {
    // Below the floor: refused, never padded with fiction.
    $this->actingAs($this->owner)->from(route('content.outreach.index'))
        ->post(route('content.outreach.research-story'))
        ->assertRedirect()->assertSessionHasErrors('story');
    expect(ContentPiece::count())->toBe(0);

    for ($i = 0; $i < 12; $i++) {
        Contact::create(['first_name' => 'C'.$i, 'email' => "c{$i}@x.com"]);
    }

    $this->actingAs($this->owner)->post(route('content.outreach.research-story'))->assertRedirect();

    $piece = ContentPiece::firstOrFail();
    expect($piece->status)->toBe('draft')
        ->and($piece->title)->toContain('12 client relationships')
        ->and($piece->body)->toContain('computed live from this organization')
        ->and($piece->body)->toContain('No external, estimated or industry-average numbers');
});
