<?php

namespace App\Services\Seo;

use App\Models\BrandProfile;
use App\Models\Citation;
use App\Models\Competitor;
use App\Models\OutreachProspect;
use App\Seo\Contracts\LinkDataProvider;

/**
 * LINK-001/002/003: the backlink audit over the link-index seam, plus the
 * platform's own FIRST-PARTY verified links (outreach placements + citations,
 * real regardless of driver). Toxicity is heuristic and every flag names its
 * reason; the disavow export is Google's actual format.
 */
class BacklinkAuditService
{
    /** DA at or below this is a toxicity signal. */
    public const TOXIC_DA = 10;

    private const SPAM_TLDS = ['.xyz', '.top', '.click', '.link', '.work', '.loan', '.gq'];

    private const MONEY_ANCHORS = ['managed it services', 'it support company', 'msp services', 'it services near me'];

    public function __construct(private LinkDataProvider $links) {}

    /**
     * The tenant's own domain from the brand profile (host only).
     */
    public function ownDomain(): ?string
    {
        $url = BrandProfile::first()?->website_url;

        if ($url === null || $url === '') {
            return null;
        }

        return parse_url(str_contains($url, '://') ? $url : 'https://'.$url, PHP_URL_HOST) ?: null;
    }

    /**
     * LINK-001/002: provider links for our domain, each row carrying its
     * toxicity verdict, plus summary counts and the first-party verified set.
     *
     * @return array{domain: string|null, provider: string, links: list<array<string, mixed>>, referring_domains: int, avg_da: int|null, toxic: int, verified: list<array{source: string, url: string|null, kind: string}>}
     */
    public function audit(): array
    {
        $domain = $this->ownDomain();
        $rows = [];

        if ($domain !== null) {
            foreach ($this->links->backlinks($domain) as $link) {
                $reasons = $this->toxicReasons($link);
                $rows[] = $link + ['toxic' => $reasons !== [], 'reasons' => $reasons];
            }
        }

        $verified = OutreachProspect::whereNotNull('placement_url')->get()
            ->map(fn (OutreachProspect $p) => ['source' => (string) ($p->domain ?: $p->name), 'url' => $p->placement_url, 'kind' => 'placement'])
            ->merge(Citation::whereNotNull('url')->get()
                ->map(fn (Citation $c) => ['source' => $c->source, 'url' => $c->url, 'kind' => 'citation']))
            ->values()->all();

        $das = array_column($rows, 'domain_authority');

        return [
            'domain' => $domain,
            'provider' => $this->links->name(),
            'links' => $rows,
            'referring_domains' => count(array_unique(array_column($rows, 'source_domain'))),
            'avg_da' => $das !== [] ? (int) round(array_sum($das) / count($das)) : null,
            'toxic' => count(array_filter($rows, fn (array $r) => $r['toxic'])),
            'verified' => $verified,
        ];
    }

    /**
     * LINK-002: Google's disavow file format for every flagged domain.
     */
    public function disavowTxt(): string
    {
        $audit = $this->audit();
        $domains = collect($audit['links'])
            ->filter(fn (array $r) => $r['toxic'])
            ->pluck('source_domain')->unique()->sort()->values();

        $lines = [
            '# Disavow file generated by Piotrack '.now()->toDateString(),
            '# Flags: DA <= '.self::TOXIC_DA.', spam TLDs, exact-match commercial anchors.',
            '# Review before uploading to Google Search Console.',
        ];
        foreach ($domains as $domain) {
            $lines[] = 'domain:'.$domain;
        }

        return implode("\n", $lines)."\n";
    }

    /**
     * LINK-003: domains linking to a tracked competitor but not to us —
     * the outreach gap list.
     *
     * @return list<array{competitor: string, source_domain: string, domain_authority: int, anchor: string}>
     */
    public function competitorGaps(): array
    {
        $domain = $this->ownDomain();
        $ours = $domain !== null
            ? array_unique(array_column($this->links->backlinks($domain), 'source_domain'))
            : [];

        $gaps = [];
        foreach (Competitor::where('is_tracked', true)->whereNotNull('domain')->get() as $competitor) {
            foreach ($this->links->backlinks((string) $competitor->domain) as $link) {
                if (! in_array($link['source_domain'], $ours, true) && $this->toxicReasons($link) === []) {
                    $gaps[] = [
                        'competitor' => $competitor->name,
                        'source_domain' => $link['source_domain'],
                        'domain_authority' => $link['domain_authority'],
                        'anchor' => $link['anchor'],
                    ];
                }
            }
        }

        return collect($gaps)->unique('source_domain')->sortByDesc('domain_authority')->values()->all();
    }

    /**
     * @param  array{source_domain: string, url: string, anchor: string, domain_authority: int}  $link
     * @return list<string>
     */
    private function toxicReasons(array $link): array
    {
        $reasons = [];

        if ($link['domain_authority'] <= self::TOXIC_DA) {
            $reasons[] = __('DA :da', ['da' => $link['domain_authority']]);
        }
        foreach (self::SPAM_TLDS as $tld) {
            if (str_ends_with($link['source_domain'], $tld)) {
                $reasons[] = __('spam TLD (:tld)', ['tld' => $tld]);

                break;
            }
        }
        if (in_array(mb_strtolower($link['anchor']), self::MONEY_ANCHORS, true)) {
            $reasons[] = __('exact-match commercial anchor');
        }

        return $reasons;
    }
}
